name: Production Build

on:
  push:
    branches: [main]

jobs:
  build-frontend:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: client

      - name: Build frontend
        run: npm run build
        working-directory: client

      - name: Build backend binary
        run: |
          make clean
          make build

#      - name: Cache npm dependencies
#        uses: actions/cache@v2
#        with:
#          path: client/node_modules
#          key: ${{ runner.os }}-node-${{ hashFiles('client/package-lock.json') }}
#          restore-keys: |
#            ${{ runner.os }}-node-
